server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service


mybatis:
  mapper-locations: mappers/**/*.xml #文件地址
  type-aliases-package: cn.itcast.springboot.pojo #别名扫描
  configuration:
    map-underscore-to-camel-case: true #开启驼峰